playbooks/pre-install-playbook/README.md
playbooks/pre-install-playbook/inventory
playbooks/pre-install-playbook/viya_pre_install_playbook.yml

Adding the initial playbook and README.md files for the pre-installation project.

Initial playbook for pre-installation validation

---

README.md

Updating wording and removed the disclaimer section as items listed there are covered under the Apache 2.0 License included with this repository. A summary of this license and its information is included in this document to eliminate any confusion.

Updating wording of README.md file

---

playbooks/pre-install-playbook/README.md

Updated the example commands to have the correct playbook file name.

Command update

---

playbooks/pre-install-playbook/README.md

Updated Viya and Ansible versions needed for Viya 3.2

Updating Viya 3.2 content

---

README.md

Updating the textual context to reflect the new Viya 3.2/3.3 branches.

Updating README.md file with new branch updates

---

playbooks/pre-install-playbook/README.md

As the number of tags grows this was not ideal to maintain. The command to list the tasks of the playbook is identified on this page and can be run at the customer's convenience.

Removing sample tags

---

playbooks/pre-install-playbook/va_pre_install_playbook.yml

this is an example on how to override the default values

example variable override

---

playbooks/pre-install-playbook/README.md

let people use higher version of Ansible

---

playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.ssh_maxstartups_config.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.ulimit_config.yml

a few of the debug tasks had no name. 
this made the output of "--list-tasks" a bit ugly. 
I've now straightened out those tasks, as well as a set_fact one.

Viya.3 3 dev fix debug tasks

---

playbooks/pre-install-playbook/roles/virk.preinstall/defaults/main.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.network_and_bandwidth_check.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.os_firewall_config.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.os_version_check.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.required_packages_config.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.selinux_config.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.yum_cache_config.yml
playbooks/pre-install-playbook/roles/virk.preinstall/vars/RedHat.yml
playbooks/pre-install-playbook/roles/virk.preinstall/vars/Suse.yml
playbooks/pre-install-playbook/roles/virk.preinstall/vars/default.yml

These are the initial changes to provide SUSE/SLES support for pre_install_playbook.

Initial SUSE/SLES support changes for Viya 3.4 pre-install playbook

---

playbooks/pre-install-playbook/roles/virk.preinstall/defaults/main.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.ulimit_config.yml

Updating this role to configure limits in /etc/security as SuSE may/does not use the /set/security/limits.d

Adding ulimit changes for SusE

---

playbooks/pre-install-playbook/roles/virk.preinstall/tasks/main.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.max_os_tasks_config.yml

Adding max_os_tasks_config role

Adding max_os_tasks_config

---

README.md
playbooks/pre-install-playbook/README.md
playbooks/pre-install-playbook/roles/virk.preinstall/defaults/main.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/main.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.cpu_check.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.max_os_tasks_config.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.network_and_bandwidth_check.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.os_firewall_config.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.os_version_check.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.required_packages_config.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.selinux_config.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.ulimit_config.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.yum_cache_config.yml
playbooks/pre-install-playbook/roles/virk.preinstall/vars/RedHat.yml
playbooks/pre-install-playbook/roles/virk.preinstall/vars/Suse.yml
playbooks/pre-install-playbook/roles/virk.preinstall/vars/default.yml

Merging in dev code into the main 3.4 branch.

Viya 3.4 dev

---

playbooks/pre-install-playbook/roles/virk.preinstall/defaults/main.yml
playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.network_and_bandwidth_check.yml

Up until now, the code was trying to count NICs. 
It should have been counting the IPs. (Private IPs). 
(see [this issue](https://github.com/sassoftware/virk/issues/21) for more details).

Viya 3.3 dev fix NIC ccount

---

playbooks/pre-install-playbook/viya_pre_install_playbook.yml

Minimal Ansible version for Viya 3.4 is now 2.4 and not 2.2

Updating minimal ansible version

---

playbooks/pre-install-playbook/roles/virk.preinstall/tasks/pre.ssh_maxstartups_config.yml

Updating maxstartups check to include case where maxstartups value is set to 100.  Also adding debugging statement to print full maxstartups settings.

Update maxstartups check

---

README.md

Updating all development branches to warn potential users this branch is used for internal development and testing.

Added warning

---

utilities/postgres/viya/README.md
utilities/postgres/viya/sds_micro_service_pg_connection_test.sh

Adding in the new postgres utility along with the new 'utilities' directory and its various items.

Adding in new Postgres utility

---

utilities/postgres/viya/README.md

Added in changes proposed by Venkata. Changed the way one accesses our official documentation to include the base link and then bread crumbs. This helps if the docs are ever updated.

Adding in Venkata's updates

---

README.md
playbooks/pre-install-playbook/README.md

Edits to the README file in the master branch

README edits

---

playbooks/home-directory-creator/README.md

Edited the Readme for the Home Dir Creator PB.

Viya 3.3 Home Dir Readme

---

playbooks/home-directory-creator/README.md

Edited the Readme in the 3.4 branch.

Viya 3.4 Home Directory Creator Readme

---

playbooks/home-directory-creator/README.md
playbooks/pre-install-playbook/README.md

Viya 3.3 dev
